// Generates dist/ from tokens/*.tokens.json (DTCG 2025.10). No dependencies.
//   dist/tokens.css          CSS custom properties (--pm-*), reduced-motion rule, type utility classes
//   dist/legacy-aliases.css  old portfolio variable names -> tokens (delete once migration is done)
//   dist/tokens.resolved.json  every token fully resolved (for Figma sync and other tools)
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadTokens, isRef, refPath, resolve, cssVar, fmt, toPx, fluid } from './lib.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = loadTokens(join(root, 'tokens'));
const FLUID = 'com.perceptionmanager.fluid';
const CSSX = 'com.perceptionmanager.css';
const SKIP_IN_CSS = new Set(['breakpoint']); // custom properties can't be used inside @media

const ref = (v) => `var(${cssVar(refPath(v))})`;
const dimension = (d) => (d.value === 0 ? '0' : `${fmt(d.value)}${d.unit}`);

function color(v) {
  if (isRef(v)) return ref(v);
  const a = v.alpha ?? 1;
  if (a === 1 && v.hex) return v.hex.toLowerCase();
  const [r, g, b] = v.components.map((c) => Math.round(c * 255));
  return `rgb(${r} ${g} ${b} / ${fmt(a)})`;
}

function shadowLayer(s) {
  const d = (x) => (isRef(x) ? ref(x) : dimension(x));
  const spread = isRef(s.spread) || s.spread.value !== 0 ? ` ${d(s.spread)}` : '';
  return `${s.inset ? 'inset ' : ''}${d(s.offsetX)} ${d(s.offsetY)} ${d(s.blur)}${spread} ${color(s.color)}`;
}

/** Returns [[name, value], ...] for one token. Typography expands into several properties. */
function declarations(path, t) {
  const v = t.$value;
  const name = cssVar(path);
  if (t.$type === 'typography') {
    if (isRef(v)) { // component alias of a type role
      const role = refPath(v).split('.').pop();
      return ['size', 'line-height', 'weight', 'family', 'tracking'].map((p) => [`${name}-${p}`, `var(--pm-type-${role}-${p})`]);
    }
    const role = path.split('.').pop();
    const fl = t.$extensions?.[FLUID];
    const css = t.$extensions?.[CSSX] ?? {};
    const size = fl ? fluid(toPx(fl.min), toPx(fl.max), fl.viewport.min, fl.viewport.max) : ref(v.fontSize);
    const out = [
      [`--pm-type-${role}-size`, size],
      [`--pm-type-${role}-line-height`, isRef(v.lineHeight) ? ref(v.lineHeight) : fmt(v.lineHeight)],
      [`--pm-type-${role}-weight`, isRef(v.fontWeight) ? ref(v.fontWeight) : String(v.fontWeight)],
      [`--pm-type-${role}-family`, isRef(v.fontFamily) ? ref(v.fontFamily) : family(v.fontFamily)],
      [`--pm-type-${role}-tracking`, css.tracking ? ref(css.tracking) : dimension(v.letterSpacing)],
    ];
    return out;
  }
  if (isRef(v)) return [[name, ref(v)]];
  switch (t.$type) {
    case 'color': return [[name, color(v)]];
    case 'dimension': {
      const fl = t.$extensions?.[FLUID];
      return [[name, fl ? fluid(toPx(fl.min), toPx(fl.max), fl.viewport?.min ?? 375, fl.viewport?.max ?? 1280) : dimension(v)]];
    }
    case 'fontFamily': return [[name, family(v)]];
    case 'fontWeight': return [[name, String(v)]];
    case 'number': return [[name, path.startsWith('font.tracking') ? (v === 0 ? '0' : `${fmt(v)}em`) : fmt(v)]];
    case 'duration': return [[name, `${v.value}${v.unit}`]];
    case 'cubicBezier': return [[name, v.join() === '0,0,1,1' ? 'linear' : `cubic-bezier(${v.map(fmt).join(', ')})`]];
    case 'shadow': return [[name, (Array.isArray(v) ? v : [v]).map(shadowLayer).join(', ')]];
    case 'gradient': {
      const angle = t.$extensions?.[CSSX]?.angle ?? '180deg';
      return [[name, `linear-gradient(${angle}, ${v.map((s) => `${color(s.color)} ${fmt(s.position * 100)}%`).join(', ')})`]];
    }
    case 'transition': return [[name, `${isRef(v.duration) ? ref(v.duration) : `${v.duration.value}${v.duration.unit}`} ${isRef(v.timingFunction) ? ref(v.timingFunction) : `cubic-bezier(${v.timingFunction.map(fmt).join(', ')})`}`]];
    default: throw new Error(`No CSS output rule for $type "${t.$type}" (${path})`);
  }
}

function family(list) {
  return (Array.isArray(list) ? list : [list]).map((f) => (/\s/.test(f) ? `'${f}'` : f)).join(', ');
}

// ---------------------------------------------------------------- tokens.css
const lines = [
  '/* perceptionmanager design tokens — GENERATED by scripts/build.mjs from tokens/*.tokens.json (DTCG 2025.10).',
  '   Do not edit by hand: change the JSON and run `npm run build`. */',
  '@layer tokens {',
  '  :root {',
  '    color-scheme: dark;',
];
let group = '';
let tier = '';
for (const [path, t] of tokens) {
  const top = path.split('.')[0];
  if (SKIP_IN_CSS.has(top)) continue;
  if (t.tier !== tier) { tier = t.tier; lines.push('', `    /* ===== ${tier} ===== */`); group = ''; }
  const g = path.split('.').slice(0, top === 'color' ? 2 : 1).join('.');
  if (g !== group) { group = g; lines.push(`    /* ${g} */`); }
  for (const [n, val] of declarations(path, t)) lines.push(`    ${n}: ${val};`);
}
const durations = [...tokens.keys()].filter((p) => tokens.get(p).$type === 'duration');
lines.push('  }', '', '  @media (prefers-reduced-motion: reduce) {', '    :root {');
for (const p of durations) lines.push(`      ${cssVar(p)}: 0ms;`);
lines.push('    }', '  }', '}', '');

// type utility classes
lines.push('/* One utility class per type role. Products can use these or the --pm-type-* variables directly. */', '@layer base {');
for (const [path, t] of tokens) {
  if (t.$type !== 'typography' || !path.startsWith('typography.')) continue;
  const r = path.split('.').pop();
  const tt = t.$extensions?.[CSSX]?.textTransform;
  lines.push(`  .pm-text-${r} { font-family: var(--pm-type-${r}-family); font-size: var(--pm-type-${r}-size); font-weight: var(--pm-type-${r}-weight); line-height: var(--pm-type-${r}-line-height); letter-spacing: var(--pm-type-${r}-tracking);${tt ? ` text-transform: ${tt};` : ''} }`);
}
lines.push('}', '');

// ---------------------------------------------------------------- legacy aliases
const LEGACY = {
  '--bg': 'color.surface.page', '--bg-panel': 'color.surface.raised', '--bg-card': 'color.surface.card',
  '--line': 'color.border.subtle', '--ink': 'color.text.primary', '--ink-dim': 'color.text.secondary',
  '--ink-faint': 'color.text.tertiary', '--coral': 'color.accent.primary', '--cyan': 'color.accent.secondary',
  '--grad': 'gradient.brand', '--nav-height': 'layout.nav-height', '--wrap-max': 'layout.content-max', '--wrap-pad': 'layout.gutter',
};
const legacy = [
  '/* Legacy aliases — GENERATED. Maps the portfolio\'s original variable names to tokens so pages can migrate one at a time.',
  '   Load after tokens.css. Remove once no page references the old names. */',
  '@layer tokens {', '  :root {',
  ...Object.entries(LEGACY).map(([o, p]) => {
    if (!tokens.has(p)) throw new Error(`Legacy alias ${o} points at missing token ${p}`);
    return `    ${o}: var(${cssVar(p)});`;
  }),
  '  }', '}', '',
];

// ---------------------------------------------------------------- resolved JSON
const resolved = {};
for (const [path, t] of tokens) {
  resolved[path] = { type: t.$type, tier: t.tier, value: resolve(tokens, t.$value), ...(isRef(t.$value) ? { aliasOf: refPath(t.$value) } : {}), ...(t.$extensions ? { extensions: t.$extensions } : {}) };
}

const dist = join(root, 'dist');
mkdirSync(dist, { recursive: true });
writeFileSync(join(dist, 'tokens.css'), lines.join('\n'));
writeFileSync(join(dist, 'legacy-aliases.css'), legacy.join('\n'));
writeFileSync(join(dist, 'tokens.resolved.json'), JSON.stringify(resolved, null, 2) + '\n');
console.log(`Built ${tokens.size} tokens → dist/tokens.css, dist/legacy-aliases.css, dist/tokens.resolved.json`);
